### PR TITLE
ASUB-8193 ASUB-8192 Google reCaptcha v2 & v3

### PR DESCRIPTION
**Pull request by LauraPinilla**
**Be sure to run `npm test`, `npm run lint`, and write detailed test steps before requesting reviewers**

## Description
[ASUB-8193](https://arcpublishing.atlassian.net/browse/ASUB-8193)
[ASUB-8192](https://arcpublishing.atlassian.net/browse/ASUB-8192)

Screenshot 2024-04-03 at 8 26 33 p m

We created a BotChallengeProtection component into arc-themes-blocks. But since it will be shared across different blocks: Identity-blocks & subscriptions-block, we are moving this component into this repo.

If you want to see this on play with the arc-themes-blocks, please use the cdn endpoint 
https://subssinglesite-the-daily-intelligencer-sandbox.api.cdn.arcpublishing.com. This tenant has the reCaptcha as part of the settings. Also, I have a PR on fly (https://github.com/WPMedia/arc-themes-blocks/pull/2068) which uses this component

The code that is being moved in on the following PRs:
https://github.com/WPMedia/arc-themes-blocks/pull/1978 >> reCaptchaV2
https://github.com/WPMedia/arc-themes-blocks/pull/2031 >> reCaptchaV3

BotChallengeProtection component will accept a challengeIn attribute. This attribute could be one of:
'signup' || ‘signin’ || ‘magiclink’ || ‘checkout’

**reCaptchaV3**
reCaptcha v3 does not require action by the user, the recaptcha is returned automatically.

IF !!`${challengeIn}Recaptcha && (0 <=recaptchaScore && recaptchaScore <= 1) && !!recaptchaSiteKey
THEN render reCaptchaV3. reCaptchaV3 should be initialized by passing the recaptchaSiteKey

**reCaptchaV2**
reCaptcha v2 does require action by the user
IF !!`${challengeIn}Recaptcha && recaptchaScore between 0 - 1 &&!!recaptchaSiteKey

_Information about what you changed for this PR. Include any dependencies, companion PRs, relevant screenshots, or config changes._

## Test Steps

_Add detailed test steps a reviewer must complete to test this PR_

1. Checkout this branch - `git checkout {branch name}`
2. Update dependencies - `npm i`
3. Run Storybook `npm run storybook`
4. {Next ....}

[ASUB-8193]: https://arcpublishing.atlassian.net/browse/ASUB-8193?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[ASUB-8192]: https://arcpublishing.atlassian.net/browse/ASUB-8192?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by malavikakoppula — CHANGES_REQUESTED** [review]
@LauraPinilla can you fix lint errors and also tests are not meeting the threshold(80%).

**Comment by LauraPinilla** [comment]
> @LauraPinilla can you fix lint errors and also tests are not meeting the threshold(80%).

Hi @malavikakoppula It's weird. When I'm running this locally, I cannot see linting or test errors. Do you mind taking a look. It's my first time working on this rep. Thanks. 

Screenshot 2024-04-05 at 12 33 21 p m

btw. I just pushed a commit since I noticed I was missing some styles

**Review by malavikakoppula — APPROVED** [review]
LGTM

**Review by edwardcho1231 — APPROVED** [review]
LGTM. Thanks

**Pull request merged**
