### PR TITLE
TMEDIA-653 ci : Use uniform pattern for caching dependencies accross GitHub Actions

### PR DESCRIPTION
**Pull request by ecarlisle**
## Description
Ensure github action caching uniformity 

## Jira Ticket
- [TMEDIA-653](https://arcpublishing.atlassian.net/jira/software/c/projects/TMEDIA/boards/875?modal=detail&selectedIssue=TMEDIA-653)

## Acceptance Criteria
Github actions caching is uniformly done throughout blocks, themes components, and engine theme sdk

## Note 
This PR reverted commit 3c7beadf6b17032c221631d2c86eba3a3cea8fad.

Write a doc in the themes internal space around caching and best practices there 

Make sure that the cache is reset when there’s a change to the package-lock and used when there’s no change to the package-lock

## Test Steps
- See example in lerna playground where this structure and investigation works https://github.com/WPMedia/themes-lerna-playground/pull/15

### Before
- Unnecessary caching and potentially not enough installing

### After
- Unnecessary caching and potentially not enough installing

## Review Checklist
_The author of the PR should fill out the following sections to ensure this PR is ready for review._
- [ ] Confirmed all the test steps above are working
- [ ] Confirmed there are no linter errors
- [ ] Confirmed this PR has reasonable code coverage
  - [ ] Confirmed this PR has unit test files
  - [ ] Ran `npm test`, made sure all tests are passing
  - [ ] If the amount of work to write unit tests for this change are excessive,
please explain why (so that we can fix it whenever it gets refactored).
- [ ] Confirmed relevant documentation has been updated/added.

### CODE REVIEW

**Comment by matthewroach** [comment]
Why are we reverting?

**Comment by ecarlisle** [comment]
> Why are we reverting?

cc: @JackHowa

**Comment by ecarlisle** [comment]
> > Why are we reverting?
> 
> cc: @JackHowa

@matthewroach : Sorry, changed the title of the commit. @JackHowa and I are confirming the PR approval workflow. Will re-implement changes, have @JackHowa approve, and will re-merge.

**Comment by ecarlisle** [comment]
Confirmed actions are consistent that run w/ PR and push:
image

**Comment by JackHowa** [comment]
working as expected based on discussions

**Pull request closed without merging**
