### PR TITLE
Tmedia 660 prettier ticket

### PR DESCRIPTION
**Pull request by JackHowa**
Testing Instructions: 

1. Add a comment in a file with lots of spaces 
2. Add and commit the file
3. See the pre-commit change https://github.com/WPMedia/arc-themes-components/pull/24/commits/8bf2c114dfe2413073746834422f22f00a497341
4. Locally, you should see linting (below) and prettier updates with vs code on save. I updated the vs code workspace settings
Screen Shot 2022-02-22 at 09 18 04
5. `npm run format` should prettier-ify all compatible code 
6. `npm run lint` should have no contradictory issues with prettier due to eslint config 

Questions: 

- Double- or single-quotes? it looks like prettier has a default of double; this can be changed back 

-> Matthew prefers double 

- I can get lint-staged working on commit. I may need to do more research to get the actual formatting of code to work on push. It's super quick on commit though (and if you use vs code or ide formatting, you'll never see it). is this one on commit action ok? 

-> based on feedback, and the user experience, yes

AC: 

Install prettier 

Incorporate prettier with eslint via eslint-prettier

Formats all code in the repo 

On push, prettier should run and format the code and push that formatted code. (lint-staged does this well.) 

Applies to arc-themes-blocks, arc-themes-components, and engine-theme-sdk

Build works in engine-theme-sdk

### CODE REVIEW

**Comment by matthewroach** [comment]
> Double- or single-quotes? it looks like prettier has a default of double; this can be changed back

I prefer double quotes over single

For the on commit - I don't mind that either, it is very quick and would not be very invasive to the developer

**Comment by matthewroach** [comment]
The default config for line length in prettier is `80` - This has always felt a little short in my opinion, what you think about increasing it to say `120`?
Some of the changes applied in this PR with the default of `80` to me makes the code a little un readable

**Comment by JackHowa** [comment]
> The default config for line length in prettier is `80` - This has always felt a little short in my opinion, what you think about increasing it to say `120`? Some of the changes applied in this PR with the default of `80` to me makes the code a little un readable

Maybe 100? I find this a tad hard to read full width of anything more than 100. I tend to use split screen anyways when writing code so it's kind of hard to generalize on this though.  @matthewroach 

Screen Shot 2022-02-23 at 09 06 57

For example, line length of 80 in split screen (at 100) looks ok with word wrap 

before with 80 (left) and after with 100 (right)

Screen Shot 2022-02-23 at 09 10 13

If it was entirely up to me, I'd prefer 80 due to primarily using split screen with a more zoomed-in font size for readability. I've used word wrap but I'd prefer not to have to rely upon it extensively. 

I'd be curious what other team members think.  @visionbegin @ecarlisle @nschubach 

https://prettier.io/docs/en/options.html prettier line length options

**Comment by matthewroach** [comment]
line length of a `100` is better than `80` 😉

**Comment by RobinGiannattasio** [comment]
> line length of a `100` is better than `80` 😉

monk symmetry

**Comment by nschubach** [comment]
I know I'm late on this, but I prefer single quotes ( fewer keystrokes :p ) but I'm not hard-lined on that.  In languages like C the double quote is a string array where the single is a single character string, but in JS it doesn't matter.  Double quotes feel "cluttery" as they are more complex looking, but I also like enforced semi-colons (shakes fist at ASI) so I don't mind clutter.  JSON spec requires double quotes though, so going back and forth might be annoying.  Single quotes can probably also be confusing with backticks being a thing now.  I'm "whatever" on this.

I never liked enforced line lengths, but if we have them... 80 is just too small, 100 works.

I do like enforced new lines at the end of file.  Can we get that in to avoid this stuff?
image

Yes!
image

This feels odd to me:
image

**Comment by JackHowa** [comment]
@nschubach thanks for the input and the review.

Cool cool. `I never liked enforced line lengths, but if we have them... 80 is just too small, 100 works.` I think 100 is an ok compromise then. Will go for that. 

Hadn't thought of this one before -- interesting `Single quotes can probably also be confusing with backticks being a thing now. I'm "whatever" on this.`. 

100% `I do like enforced new lines at the end of file. Can we get that in to avoid this stuff?`

I'll see if this happens with 100 and can investigate further. What would you expect to happen? In essence, do you dislike the new line for within the parenthesis? the `>=` on a new line?
image

**Comment by nschubach** [comment]
@JackHowa 

> In essence, do you dislike the new line for within the parenthesis? the >= on a new line?

I think the newline after the operator is a big part of it here.  The SCSS if statement doesn't have the required parens so maybe that's where it feels off to me.

**Comment by RobinGiannattasio** [comment]
In reference to the single quotes conversation: theme settings UI and API use single quotes. It's not a big deal to have them be different since devs will likely not be jumping back and forth, but there are still cases where I see the benefit of keeping it consistent. Plus I like 'em better.

I didn't check, but if there is no comma dangle, I'll fight you ;)

**Comment by nschubach** [comment]
> I didn't check, but if there is no comma dangle, I'll fight you ;)

[Dangle is in action.](https://cdn.thisisreno.com/conradcomm/wp-content/uploads/2020/01/lt-dangle-scaled-e1578806260363.jpg)

**Comment by matthewroach** [comment]
That's the benefit of having prettier in place - format is handled for us - the single vs double quotes doesn't have that much impact as it's going to auto change on push anyway. My main reason for double quotes is that coming from a HTML background attributes wold always be in double quotes and having a mix of double and single in files is not consistent, oh my OCD! 😉

**Comment by JackHowa** [comment]
I think this is ready for review if there's no other feedback. Staying in line with theme settings via the single- vs double-quotes is a good point @RobinGiannattasio from a dev experience perspective. I'm neutral on quotes but I don't see any incompatibility issues. 

@nschubach looking a tad less wonky with 100 width than 80: 

Screen Shot 2022-02-23 at 13 52 26

**Comment by nschubach** [comment]
> My main reason for double quotes is that coming from a HTML background attributes wold always be in double quotes and having a mix of double and single in files is not consistent, oh my OCD!

I always used doubles in HTML/JSX for that reason, but when in JavaScript, I always used the single quote.  So having something in-lined in a JSX tag you could easily see what was a property and what was a JS string.
`<Tag property="value" calculated={ CONST_VALUE + 'px' } />`
So one is clearly a constant string and the other is a JS derived string.  /shrug

**Review by matthewroach — APPROVED** [review]

**Comment by JackHowa** [comment]
@visionbegin @nschubach can you review this as well?

**Review by nschubach — APPROVED** [review]

**Pull request merged**
