### PR TITLE
add use sales

### PR DESCRIPTION
**Pull request by edwardcho1231**
## Ticket

- [THEMES-](https://arcpublishing.atlassian.net/browse/THEMES-)

## Description

_Information about what you changed for this PR_

## Acceptance Criteria

_copy from ticket_

## Test Steps

1. Checkout branch - `git checkout {branch-name}`
2. Update dependencies - `npm i`
3. Run Storybook `npm run storybook`
4. Check out the button storybook documentation

## Author Checklist

_The author of the PR should fill out the following sections to ensure this PR is ready for review._

- [ ] Confirmed all the test steps a reviewer will follow above are working.
- [ ] Ran this code locally and checked that there are not any unintended side effects. For example, that a CSS selector is scoped only to a particular block.
- [ ] Confirmed relevant documentation has been updated/added.
- [ ] Add label - **ready for review** when the pull request is ready for someone to begin reviewing

## Reviewer Checklist

_The reviewer of the PR should copy-paste this template into the review comments on review._

- [ ] All GitHub Actions pass
- [ ] Ran the code locally based on the test instructions.
- [ ] Checked Chromatic for Storybook changes, accepted the updates if acceptable
- [ ] Looked to see that the new or changed code has code coverage, specifically. We want the global code coverage to keep on going up with targeted testing.
- [ ] Approve and Add label - **ready to merge** if you are happy with the pull request
- [ ] Want another reviewer? Add the label **additional review**

### CODE REVIEW

**Comment by vgalatro** [comment]
This hook will need to be imported/exported from the root `index.js` as well so it can be imported from `arc-themes-components` in other projects.

**Review by nschubach — APPROVED** [review]
Looks good to me otherwise

**Review by nschubach — CHANGES_REQUESTED** [review]
Didn't see Vito's comment, I agree.  It should be set up to export the hook

**Comment by vgalatro** [comment]
Also this will need to go into 2.3.0 once the branch is created, as we're launching 2.2.1 soon with security hotfixes.

**Review by LauraPinilla — APPROVED** [review]
LGTM!

**Comment by edwardcho1231** [comment]
@vgalatro Can I get another look? I think this needs to be merged first as recaptcha pr uses this hook. Thanks.

**Review by vgalatro — APPROVED** [review]
@edwardcho1231 , LGTM! You're right this would need to be merged first.

**Pull request merged**
