### PR TITLE
Add formatSocialURL

### PR DESCRIPTION
**Pull request by nschubach**
## Ticket

- [TMEDIA-717](https://arcpublishing.atlassian.net/browse/TMEDIA-717)
- [TMEDIA-758](https://arcpublishing.atlassian.net/browse/TMEDIA-758)

## Description

Moving formatSocialULR into components util

## Acceptance Criteria

n/a

## Test Steps

1. Checkout branch - `git checkout add-format-social-url`
2. Run Storybook `npm run storybook`
4. Check out the button storybook documentation

## Author Checklist

- [x] Confirmed all the test steps a reviewer will follow above are working.
- [x] Ran this code locally and checked that there are not any unintended side effects. For example, that a CSS selector is scoped only to a particular block.
- [x] Confirmed relevant documentation has been updated/added.
- [x] Add label - **ready for review** when the pull request is ready for someone to begin reviewing

## Reviewer Checklist

_The reviewer of the PR should copy-paste this template into the review comments on review._

- [ ] All GitHub Actions pass
- [ ] Ran the code locally based on the test instructions.
- [ ] Checked Chromatic for Storybook changes, accepted the updates if acceptable
- [ ] Looked to see that the new or changed code has code coverage, specifically. We want the global code coverage to keep on going up with targeted testing.
- [ ] Approve and Add label - **ready to merge** if you are happy with the pull request
- [ ] Want another reviewer? Add the label **additional review**

### CODE REVIEW

**Review by malavikakoppula — APPROVED** [review]
LGTM

**Review by ecarlisle — CHANGES_REQUESTED** [review]
The code looks good. The tests pass. I'm expecting to see the full URL in Storybook instead of just the social moniker input. 🤔 
image

**Comment by nschubach** [comment]
> 

My last update fixes this.

**Review by ecarlisle — APPROVED** [review]
- [X] All GitHub Actions pass
- [X] Ran the code locally based on the test instructions.
- [X] Checked Chromatic for Storybook changes, accepted the updates if acceptable
- [X] Looked to see that the new or changed code has code coverage, specifically. We want the global code coverage to keep on going up with targeted testing.
- [X] Approve and Add label - ready to merge if you are happy with the pull request

**Pull request merged**
