### PR TITLE
THEMES-1864: Button styling fix

### PR DESCRIPTION
**Pull request by vgalatro**
#### Jira Ticket: [THEMES-1864](https://arcpublishing.atlassian.net/browse/THEMES-1864)

This PR fixes the styling for the button component. It was out of sync with what is in the Figma style docs. The button styles are located here: https://www.figma.com/design/NBjMF1v4mzwv9jkn7NEq9V/Themes-Block-Styling-2.0?node-id=10862-135976&t=YU12KWjCz73C7KdP-0.

## Test Steps

1. Checkout this branch - `git checkout THEMES-1864`
2. Update dependencies - `npm i`
3. Run Storybook `npm run storybook`
4. Verify that the Button variants (on this page with storybook running http://localhost:6006/?path=/story/components-button--button-variants) `Primary`, `Primary-reverse`, `Secondary`, and `Secondary-reverse` match the Figma docs. Check both the at rest and hover states.

[THEMES-1864]: https://arcpublishing.atlassian.net/browse/THEMES-1864?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by malavikakoppula — CHANGES_REQUESTED** [review]
@vgalatro Secondary reverse button label is not visible until hover it. In Figma, it has neutral-3 background.

Screenshot 2024-08-15 at 11 43 39 AM

Screenshot 2024-08-15 at 11 40 23 AM

**Comment by vgalatro** [comment]
@malavikakoppula , I believe that is just the box's background color and not part of the button. It's meant to be used on dark backgrounds and the colors for the rest state are listed here:
Screenshot 2024-08-15 at 12 09 45 PM

**Comment by malavikakoppula** [comment]
> @malavikakoppula , I believe that is just the box's background color and not part of the button. It's meant to be used on dark backgrounds and the colors for the rest state are listed here: Screenshot 2024-08-15 at 12 09 45 PM

So, including border, button label should also appear on hover?

**Comment by vgalatro** [comment]
@malavikakoppula , right, it's just the background for storybook is also white, which makes it hard to see.

**Review by malavikakoppula — DISMISSED** [review]
LGTM

**Review by malavikakoppula — APPROVED** [review]

**Pull request merged**
