### PR TITLE
TBRANDS 87: Remove hard-coded height from buttons for carousel

### PR DESCRIPTION
**Pull request by JackHowa**
## Ticket

- [TBRANDS-87](https://arcpublishing.atlassian.net/browse/TBRANDS-87)

## Description

Remove hard-coded height so text can grow horizontally 

## Acceptance Criteria

Text is no longer cutoff in button 

## Test Steps

Compare stories in chromatic to show the text no longer cutoff

## Deps 
- Will make feature pack updates to news and brands based on this 

## Author Checklist

- [x] Confirmed all the test steps a reviewer will follow above are working.
- [x] Ran this code locally and checked that there are not any unintended side effects. For example, that a CSS selector is scoped only to a particular block.
- [x] Confirmed relevant documentation has been updated/added.
- [x] Add label - **ready for review** when the pull request is ready for someone to begin reviewing

## Reviewer Checklist

_The reviewer of the PR should copy-paste this template into the review comments on review._

- [ ] All GitHub Actions pass
- [ ] Ran the code locally based on the test instructions.
- [ ] Checked Chromatic for Storybook changes, accepted the updates if acceptable
- [ ] Looked to see that the new or changed code has code coverage, specifically. We want the global code coverage to keep on going up with targeted testing.
- [ ] Approve and Add label - **ready to merge** if you are happy with the pull request
- [ ] Want another reviewer? Add the label **additional review**

### CODE REVIEW

**Review by matthewroach — DISMISSED** [review]

**Comment by matthewroach** [comment]
I approved the change - but looking at the storybook it's affecting buttons I wasn't expecting

**Comment by JackHowa** [comment]
gotcha I can set a min-width on it. or really only target the buttons on the top? @matthewroach

**Comment by matthewroach** [comment]
Can we just target the top buttons? Can we just set width to auto for the top buttons?

**Comment by JackHowa** [comment]
ya can do

**Comment by JackHowa** [comment]
Screen Shot 2022-06-30 at 15 58 52

updating the top buttons but not the next and previous

**Comment by JackHowa** [comment]
@haganka  related to the question of which buttons to affect the width on

**Comment by JackHowa** [comment]
based on discussion with Kelly, we want all of buttons in the carousel to scale horizontally

**Comment by haganka** [comment]
@JackHowa left a couple of comments on buttons. To recap:
- add 8px padding on right and left
- add 8px gap for buttons with icon and text
- vertically center button text/icons

**Comment by JackHowa** [comment]
@haganka @matthewroach updated based on feedback. will update feature packs based on this

**Comment by haganka** [comment]
thanks for the changes @JackHowa !

**Comment by ecarlisle** [comment]
I've confirmed that the buttons:
1. No longer have a fixed width:
image

2. have correct padding and gap:
image

3. and center align with both text and icons:
image

All looks good!

**Review by ecarlisle — APPROVED** [review]

**Pull request merged**
