### PR TITLE
TMEDIA-661: Update CSS Reset

### PR DESCRIPTION
**Pull request by nschubach**
Updating the reset to use more modern reset methodologies.

### CODE REVIEW

**Review by brentmiller1973 — APPROVED** [review]
I'm happy with the changes, however I am still sold on the idea of these reset styles being global tokens.  I think that will allow for more client flexibility and help (in a small way granted) to reduce/prevent client stylesheets.  However, if we want to just go with this, I'm not going to put up a fuss, so I am going to approve, but some thought should be given to what I am suggesting....let the tokens drive...Elon Musk would agree.

**Comment by nschubach** [comment]
Open a ticket.  ;)  I think we can easily move some of these over to tokens.

**Comment by RobinGiannattasio** [comment]
> Open a ticket. ;) I think we can easily move some of these over to tokens.

I came here to say this, but Nick already had it covered! It's definitely worth at least opening up a spike ticket to investigate whether we want to do that, and document the pros/cons/decisions

**Comment by matthewroach** [comment]
I disagree with the idea of the reset pulling values from tokens - the idea with a reset is to provide a consistent base in which all components and block are styled from

**Review by matthewroach — APPROVED** [review]

**Pull request merged**
