### PR TITLE
THEMES 774 Additional icons to be added to the Icon component

### PR DESCRIPTION
**Pull request by cedric066**
## Description

In a review of [TMEDIA-788](https://arcpublishing.atlassian.net/browse/TMEDIA-788), design noticed that there are icons in [Figma](https://www.figma.com/file/giQllWgtzGk42KwK2XD9rY/Brand-Browsing-Page-Designs?type=design&node-id=2944-34134&mode=design&t=KJxzSikwWUdJorCs-0) that aren't available in the Icon component. My job in this ticket was to add the missing icons.
  
I made the following changes:
* Each icon got a file in the `icon/icons` directory. The file contains a `path` with a path for the icon's SVG
    * Most of the icons were sourced from [Figma](https://www.figma.com/file/giQllWgtzGk42KwK2XD9rY/Brand-Browsing-Page-Designs?type=design&node-id=2944-34134&mode=design&t=KJxzSikwWUdJorCs-0), but some were sourced from the [Storybook](https://5eed0506faad4f0022fedf95-nrlvhjyiiz.chromatic.com/?path=/docs/icon--all-icons-resize) because of Figma's weird handling of SVGs. Some of the icons would have incorrect filling or be missing when they were imported directly from Figma (this held for existing icons too during my testing)
    * To resize the icons' paths for our 512 x 512 view box, I used [this website](https://aydos.com/svgedit/)
* In `icon/icons/index.js` I added lines to export all of the new icons
    * **Icon names are taken from their names in Figma**
* In `icon/index.jsx` I added all of the new icons to the `name` prop, so they can be selected in PageBuilder
* I created a test block in `arc-themes-feature-pack` to display and verify the look of the new icons (see test steps below)

## Ticket

[THEMES-774](https://arcpublishing.atlassian.net/browse/THEMES-774)

## Acceptance Criteria

1. Missing icons are added to the Icon component repository

## Test Steps

1. Checkout this branch: `git checkout THEMES-774-additional-icons`
2. Update dependencies: `npm i`
3. Run Storybook: `npm run storybook`
4. Check out the Icon storybook documentation (**"All Icons" page**)
    * Make sure all of the icons referenced in [Figma](https://www.figma.com/file/giQllWgtzGk42KwK2XD9rY/Brand-Browsing-Page-Designs?type=design&node-id=2944-34134&mode=design&t=KJxzSikwWUdJorCs-0) are present
    * Make sure the icons look good (no filling issues or obvious flaws)
5. **If you want to see the new icons in PageBuilder,** follow the steps below:
    * Go to `arc-themes-feature-pack`
    * Checkout this branch: `git checkout THEMES-774-additional-icons` (**This branch will be deleted once this ticket/branch gets merged in!**)
    * Start fusion (no blocks need to be linked) with `npx fusion start`
    * Open your local PageBuilder instance and create a new page
        * Select the Right Rail layout and insert an "icon-test default" bock in the "Main" section
    * All of the new icons will display on the page. Verify that they look good and that there are no issues with filling, sizing, etc.

### Before

The icons below were not available in PageBuilder:

Screenshot 2023-08-14 at 1 16 15 PM

### After

The icons from above are now usable in PageBuilder (ignore the color, it was for testing):

Screenshot 2023-08-14 at 1 17 22 PM Screenshot 2023-08-14 at 1 18 03 PM Screenshot 2023-08-14 at 1 24 07 PM

## Author Checklist

- [x] Confirmed all the test steps a reviewer will follow above are working.
- [x] Ran this code locally and checked that there are not any unintended side effects. For example, that a CSS selector is scoped only to a particular block.
- [x] Confirmed relevant documentation has been updated/added.
- [x] Add label - **ready for review** when the pull request is ready for someone to begin reviewing

## Reviewer Checklist

_The reviewer of the PR should copy-paste this template into the review comments on review._

- [ ] All GitHub Actions pass
- [ ] Ran the code locally based on the test instructions.
- [ ] Checked Chromatic for Storybook changes, accepted the updates if acceptable
- [ ] Looked to see that the new or changed code has code coverage, specifically. We want the global code coverage to keep on going up with targeted testing.
- [ ] Approve and Add label - **ready to merge** if you are happy with the pull request
- [ ] Want another reviewer? Add the label **additional review**

[TMEDIA-788]: https://arcpublishing.atlassian.net/browse/TMEDIA-788?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[THEMES-774]: https://arcpublishing.atlassian.net/browse/THEMES-774?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by malavikakoppula — CHANGES_REQUESTED** [review]
LGTM! except the package-lock. There's no changes to package.json right?

**Comment by cedric066** [comment]
> LGTM! except the package-lock. There's no changes to package.json right?

@malavikakoppula I ran `npm i` while making sure the testing instructions worked. I didn't do anything that would require new packages, so I reverted that commit

**Review by malavikakoppula — APPROVED** [review]
LGTM

**Comment by cedric066** [comment]
@pardistaherzadeh this is ready for design QA

**Comment by pardistaherzadeh** [comment]
@cedric066 Looks good to me!

**Pull request merged**
